name: py-plot
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23.4
  - numpy-stl=2.17.1
  - pandas
  - pinocchio
  - pip
  - pyarrow
  - pyopengl
  - pyparsing
  - pyqt=5.15
  - pyqtgraph
  - python=3.10
  - scipy
  - shtab
  - urdfpy
  - pip:
    - py-expression-eval
    - pywavefront

